[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-pc-windows-msvc", "x86_64-pc-windows-msvc"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.3"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["powershell", "msi"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true
# Whether dist should create a Github Release or use an existing draft
create-release = false
