name: MSI Preview

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-msi:
    name: Build MSI
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install dist
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.30.3/cargo-dist-installer.sh | sh

      - id: cargo-dist
        name: Build MSI
        shell: bash
        run: |
          dist build --installer msi --output-format=json > dist-manifest.json
          echo "dist ran successfully"
          echo "paths<<EOF" >> "$GITHUB_OUTPUT"
          dist print-upload-files-from-manifest --manifest dist-manifest.json >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: gpui-clipboard-manager-msi
          path: |
              target/distrib/gpui-clipboard-manager-x86_64-pc-windows-msvc-update
              target/distrib/gpui-clipboard-manager-x86_64-pc-windows-msvc.msi
              target/distrib/gpui-clipboard-manager-x86_64-pc-windows-msvc.msi.sha256
              target/distrib/gpui-clipboard-manager-x86_64-pc-windows-msvc.zip
              target/distrib/gpui-clipboard-manager-x86_64-pc-windows-msvc.zip.sha256
              target/distrib/sha256.sum
              target/distrib/source.tar.gz
              target/distrib/source.tar.gz.sha256
